Repository JokinAce/DiscordBot-ReverseEngineers, pull requests merged in 2021-03, with the labels that each got.

#24 made the changes you want
  DiscordBotEthan/EventHandlers.cs
  DiscordBotEthan/Players/Players.db
  DiscordBotEthan/Players/SQLiteController.cs
Labels: enhancement, good first issue

#28 just added __import__ to blacklisted
  DiscordBotEthan/Commands/Repython.cs
Labels: wontfix

#30 Jokin patches
  DiscordBotEthan/Commands/Clear.cs
  DiscordBotEthan/Commands/Remindme.cs
  DiscordBotEthan/Commands/Repython.cs
  DiscordBotEthan/Commands/Resharp.cs
  DiscordBotEthan/Commands/Tempmute.cs
  DiscordBotEthan/Commands/Unmute.cs
  DiscordBotEthan/Commands/Warns.cs
  DiscordBotEthan/DiscordBotEthan.csproj
  DiscordBotEthan/EventHandlers.cs
  DiscordBotEthan/Players/SQLiteController.cs
  DiscordBotEthan/Program.cs
Labels: enhancement
